% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Household Energy Consumption Analysis},
  pdfauthor={Emanuel Lemma, Raphaël Spagolla, Tharrmeehan Krishnathasan},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Household Energy Consumption Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Applied Machine Learning and Predictive Modelling 1 -- FS
2026}
\author{Emanuel Lemma, Raphaël Spagolla, Tharrmeehan Krishnathasan}
\date{2026-05-25}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(tidyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}
\FunctionTok{library}\NormalTok{(scales)}
\FunctionTok{library}\NormalTok{(broom) }\CommentTok{\# tidy model output}
\FunctionTok{library}\NormalTok{(car) }\CommentTok{\# VIF}
\FunctionTok{library}\NormalTok{(mgcv) }\CommentTok{\# GAM}
\FunctionTok{library}\NormalTok{(gratia)}
\FunctionTok{library}\NormalTok{(nnet) }\CommentTok{\# Neural Network}
\FunctionTok{library}\NormalTok{(ROCR)}
\FunctionTok{library}\NormalTok{(e1071) }\CommentTok{\# SVM}
\FunctionTok{library}\NormalTok{(caret) }\CommentTok{\# Cross{-}validation}
\FunctionTok{library}\NormalTok{(kernlab) }\CommentTok{\# SVM kernels}
\FunctionTok{library}\NormalTok{(gridExtra)}
\end{Highlighting}
\end{Shaded}

\section{Introduction}\label{introduction}

With the rapid expansion of heat pump installations across Swiss
households, electricity demand is increasingly driven by heating and
cooling needs rather than fixed consumption habits. Unlike traditional
resistive heating, heat pumps draw substantial power in short,
weather-dependent bursts. This creates load profiles that are harder to
predict and more sensitive to outdoor conditions than the
appliance-driven consumption patterns that grid operators have
historically managed.

For energy suppliers and grid operators, this shift has direct economic
consequences. Procurement decisions made a day or week in advance are
based on load forecasts. When a cold snap arrives earlier than expected
or a warm spell pushes temperatures above the heating threshold, actual
demand diverges from the submitted schedule. The resulting imbalances
must be settled at spot or balancing energy prices. These costs
ultimately flow back to households and erode the economic case for
electrification if not properly managed.

Against this background, this analysis systematically evaluates smart
meter data from a portfolio of heat pump households in Switzerland,
using the \textbf{HEAPO dataset}, in order to identify the most
important drivers of electricity consumption and build a well-founded
basis for demand modelling. The focus is not only on explaining
consumption variability across seasonal patterns, building
characteristics, and technology choices, but also on quantifying the
interaction between external factors such as outdoor temperature,
heating degree days, and building type.

The report is structured as follows. Section 2 presents exploratory data
analysis. Section 3 fits and interprets six models, namely a Linear
Model, GLM Poisson, GLM Binomial, Generalised Additive Model, Neural
Network, and Support Vector Machine. Section 4 compares model
performance. Section 5 draws conclusions for energy suppliers and grid
operators.

\subsection{Dataset}\label{dataset}

\textbf{Source:} HEAPO -- Household Energy and Smart Meter Data (Zenodo,
2025).

The HEAPO dataset was collected as part of a Swiss research project
monitoring residential heat pump installations via smart meters. It
covers 99838 household-days across 127 households observed between 2022
and 2024, paired with daily weather data from the corresponding
measurement region. Each observation represents one household on one
calendar day, with daily electricity consumption as the primary outcome
alongside a set of building, technology, and weather covariates.

\subsection{Variable Description}\label{variable-description}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{log\_kWh\_total} & Continuous & Natural log of daily total
electricity consumption (kWh). Response for LM and GAM. \\
\texttt{heating\_degree\_days} & Continuous & Daily heating demand below
the 12°C Swiss SIA base temperature (°C·day). \\
\texttt{temp\_avg} & Continuous & Daily average outdoor temperature
(°C). \\
\texttt{living\_area} & Continuous & Heated floor area of the household
(m²). \\
\texttt{building\_type} & Categorical (\textgreater2 levels) & Building
type, either ``appartment'' or ``house''. \\
\texttt{heatpump\_type} & Categorical (2 levels) & Heat pump technology:
air-source or ground-source. \\
\texttt{n\_residents} & Count & Number of permanent household
members. \\
\texttt{is\_weekend} & Binary & 1 if Saturday or Sunday, 0 otherwise. \\
\texttt{has\_floor\_heating} & Binary & 1 if floor heating system
present, 0 otherwise. \\
\texttt{high\_consumption} & Binary & 1 if daily kWh exceeds the
household's own 75th percentile (top 25\% of that household's days).
Response for GLM Binomial. \\
\end{longtable}
}

The raw HEAPO dataset spans 2018 to 2024 across 438 monitored households
in the canton of Zurich. The modelling subset was restricted to the
period 2022-01-01 through 2024-02-29 and limited to households with at
least 95\% daily coverage to exclude partially observed installations.
It was then randomly sampled to a maximum of 100,000 observations to
comply with the course data size limit.

\section{Exploratory Data Analysis}\label{exploratory-data-analysis}

Daily electricity consumption (\texttt{kWh\_total}) is right-skewed on
the raw scale and approximately symmetric after log transformation. The
log-transformed variable \texttt{log\_kWh\_total} is used as the
continuous response in all regression models. The binary variable
\texttt{high\_consumption} is derived from it. A day is classified as
high consumption if daily \texttt{log\_kWh\_total} exceeds that
household's own 75th percentile, flagging the top 25\% of consumption
days for each individual household.

\subsection{Seasonal Pattern}\label{seasonal-pattern}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{heapo }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Month =} \FunctionTok{month}\NormalTok{(date, }\AttributeTok{label =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{abbr =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Month, }\AttributeTok{y =}\NormalTok{ kWh\_total)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ clr\_primary, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{outlier.size =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Daily Electricity Consumption by Month"}\NormalTok{,}
    \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"kWh per day"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/eda-seasonal-1} \end{center}

Consumption in winter months (December to February) is roughly three to
five times higher than in summer (June to August), driven almost
entirely by heat pump operation for space heating. The wide
interquartile range in winter reflects differences in building size,
insulation quality, and heat pump technology across households. This
strong seasonal pattern motivates heating degree days as the primary
weather predictor in all models.

\subsection{Heating Degree Days
vs.~Consumption}\label{heating-degree-days-vs.-consumption}

\textbf{Heating Degree Days (HDD)} quantify daily heating demand as the
temperature shortfall below the 12°C Swiss SIA base temperature. A day
averaging 2°C contributes 10 HDD, days above 12°C contribute zero. HDD
is a more direct proxy for heat pump workload than raw outdoor
temperature.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{heapo }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{15000}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ heating\_degree\_days, }\AttributeTok{y =}\NormalTok{ kWh\_total)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.08}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_primary) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"loess"}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_secondary, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Heating Degree Days vs. Daily Consumption"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Random subsample of 15,000 observations"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Heating Degree Days (HDD)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"kWh per day"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/eda-hdd-1} \end{center}

The relationship is positive and seams to be linear across the observed
HDD range, with consumption measured form 0 to 125 kWh per day at 0
heating degree days , which hints to the base load of the building
types. The loess smoother confirms that no sharp threshold or strong
curvature is present, which justifies treating HDD as a continuous
predictor in the Linear Model. A slight levelling off at very high HDD
values is visible, and the GAM will capture this through its flexible
smooth terms.

\subsection{Consumption by Building
Type}\label{consumption-by-building-type}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{heapo }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ building\_type, }\AttributeTok{y =}\NormalTok{ kWh\_total, }\AttributeTok{fill =}\NormalTok{ building\_type)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{outlier.size =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =}\NormalTok{ clr\_builds, }\AttributeTok{guide =} \StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Daily Consumption by Building Type"}\NormalTok{,}
    \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"kWh per day"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/eda-building-1} \end{center}

Houses consume substantially more electricity per day than flats, with
medians differing by roughly a factor of two. This gap persists after
controlling for weather, as the modelling section will confirm. Building
type therefore carries real structural signal and is included as a
predictor in all models.

Taken together, the three plots tell a consistent story. Electricity
demand is primarily a seasonal phenomenon. The portfolio shifts from a
low-consumption summer baseline driven by domestic appliances to a
high-consumption winter regime dominated by heat pump space heating.
Within that seasonal pattern, building type is the strongest structural
separator, with houses drawing roughly twice the daily energy of flats
at any given temperature. These findings directly shape the modelling
choices below. The response is log-transformed to stabilise variance,
heating degree days enter as the primary continuous weather predictor,
and building type is retained as a categorical covariate in every model.
For the client, the key implication is that cold spells and the building
stock composition of a supply portfolio are the two dominant levers of
aggregate demand, and any forecasting tool must capture both to be
useful.

\section{Modelling}\label{modelling}

Six models are fitted to the HEAPO data, each targeting a response
variable suited to its statistical family. The Linear Model and
Generalised Additive Model are fitted to \texttt{log\_kWh\_total}, the
log-transformed daily electricity consumption. The GLM Binomial, Neural
Network, and Support Vector Machine all classify household-days as high
or low consumption using each household's own 75th percentile as the
threshold, capturing the top 25\% of days for each individual household.
The GLM Poisson models the monthly count of high-consumption days per
household, capturing longer-term demand patterns at a coarser
aggregation. Model performance is evaluated in the comparison section:
regression models are compared via five-fold cross-validation MAE in kWh
and R²; classification models via AUC and accuracy.

\subsection{Linear Model (LM)}\label{lm}

\emph{Lead: Tharrmeehan Krishnathasan}

\subsubsection{Objective}\label{objective}

This section models daily household energy consumption as
\(\text{log\_kWh\_total}\), the natural logarithm of total daily
kilowatt-hour usage. The log transformation is standard for energy data:
daily kWh is strictly positive and right-skewed in raw form, and
approximately normal on the log scale.

Predictors cover weather conditions (heating degree days, sunshine
hours, humidity), building characteristics (building type, living area,
heat pump type), and household composition (number of residents). Two
interaction terms are added to test whether cold-weather sensitivity
differs by building type and heat pump technology.

\subsubsection{Model Setup}\label{model-setup}

Two models are estimated:

\textbf{Simple MLR:} all seven predictors with main effects only, as an
interpretable baseline for the additive relationships between predictors
and log energy consumption:

\[
\log(\text{kWh}_i) = \beta_0 + \beta_1\,\text{HDD}_i + \beta_2\,\text{Sunshine}_i + \cdots + \beta_7\,\text{HeatpumpType}_i + \varepsilon_i
\]

\textbf{Extended MLR:} adds two interaction terms motivated by domain
knowledge:

\begin{itemize}
\tightlist
\item
  \(\text{heating\_degree\_days} \times \text{heatpump\_type}\):
  different heat pump technologies have different efficiencies in cold
  conditions, so the effect of cold on consumption should vary by pump
  type.
\item
  \(\text{heating\_degree\_days} \times \text{building\_type}\):
  well-insulated houses are less sensitive to outdoor temperature than
  poorly-insulated ones.
\end{itemize}

All coefficients are on the log scale: a coefficient of 0.05 means a 5\%
multiplicative change in kWh for a one-unit increase in the predictor.

The panel structure (multiple observations per household) means the
i.i.d. assumption of standard OLS is not fully met; standard errors may
be slightly understated due to within-household correlation.

\subsubsection{Model Results}\label{model-results}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:lm-coef-table}Extended MLR: coefficient estimates}\\
\toprule
Predictor & Estimate & Std. Error & t value & p value\\
\midrule
heating\_degree\_days & 0.0212 & 0.0029 & 7.42 & 0.000000\\
sunshine\_hours & -0.0154 & 0.0009 & -16.62 & 0.000000\\
humidity\_avg & 0.0005 & 0.0003 & 1.39 & 0.165000\\
living\_area & 0.0004 & 0.0000 & 9.78 & 0.000000\\
n\_residents & 0.1336 & 0.0026 & 50.88 & 0.000000\\
\addlinespace
building\_typehouse & 0.2199 & 0.0329 & 6.68 & 0.000000\\
heatpump\_typeground-source & -0.1427 & 0.0085 & -16.79 & 0.000000\\
heating\_degree\_days:heatpump\_typeground-source & -0.0027 & 0.0007 & -3.63 & 0.000283\\
heating\_degree\_days:building\_typehouse & 0.0392 & 0.0029 & 13.72 & 0.000000\\
\bottomrule
\end{longtabu}

All predictors are significant at the 0.001 level except
\texttt{humidity\_avg} (p = 0.165), which adds nothing once the other
weather variables are included. Effects on log energy consumption,
holding all other variables constant:

\textbf{Heating degree days} (β = 0.021, p \textless{} 0.001): Each
additional HDD increases log consumption by \textasciitilde2.1\% for
air-source pump households in flats (the baseline group).

\textbf{Sunshine hours} (β = −0.015, p \textless{} 0.001): An additional
sunshine hour reduces consumption by \textasciitilde1.5\%, reflecting
lower heating demand on brighter days.

\textbf{Number of residents} (β = 0.134, p \textless{} 0.001): Each
additional resident increases consumption by \textasciitilde14.3\%
(\(e^{0.134} - 1\)), the second strongest effect after the
temperature-building interaction.

\textbf{Building type --- house} (β = 0.220, p \textless{} 0.001):
Houses consume \textasciitilde24.6\% more than flats at baseline, before
accounting for their greater sensitivity to cold (see interaction
below).

\textbf{Heat pump type --- ground-source} (β = −0.143, p \textless{}
0.001): Ground-source pump households consume \textasciitilde13.3\% less
than air-source households at the baseline temperature.

\textbf{Interaction: HDD × house} (β = 0.039, p \textless{} 0.001):
Houses are substantially \emph{more} sensitive to cold than flats: each
additional HDD adds 3.9\% to log consumption, the largest interaction
effect in the model.

\textbf{Interaction: HDD × ground-source} (β = −0.003, p \textless{}
0.001): Ground-source pump households are slightly \emph{less} sensitive
to cold than air-source households, consistent with the higher
efficiency of ground-source systems at low outdoor temperatures.

\subsubsection{Visual Evidence}\label{visual-evidence}

The coefficient plot below summarises the direction and significance of
all predictors in the extended model.

\begin{center}\includegraphics[width=1\linewidth]{report_files/figure-latex/lm-coef-plot-1} \end{center}

The scatterplot of observed versus fitted values on the log scale
illustrates the model's predictive fit. Points near the diagonal
indicate accurate predictions.

\begin{center}\includegraphics[width=0.7\linewidth]{report_files/figure-latex/lm-obs-vs-fit-1} \end{center}

\subsubsection{Model Diagnostics}\label{model-diagnostics}

\begin{center}\includegraphics{report_files/figure-latex/lm-diagnostics-1} \end{center}

\begin{itemize}
\tightlist
\item
  \textbf{Residuals vs Fitted:} Checks linearity. A horizontal band with
  no systematic pattern is ideal.
\item
  \textbf{Q-Q Plot:} Checks normality of residuals. Points near the
  diagonal indicate normality; heavy tails would signal departure.
\item
  \textbf{Scale-Location:} Checks homoscedasticity (constant variance).
  A flat, evenly spread line is ideal.
\item
  \textbf{Residuals vs Leverage:} Identifies high-leverage observations
  that disproportionately influence the fit.
\end{itemize}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X}
\caption{\label{tab:lm-vif}Variance Inflation Factors (VIF) — extended model}\\
\toprule
Predictor & VIF\\
\midrule
heating\_degree\_days & 61.55\\
sunshine\_hours & 2.28\\
humidity\_avg & 2.09\\
living\_area & 1.04\\
n\_residents & 1.03\\
\addlinespace
building\_type & 2.18\\
heatpump\_type & 2.15\\
heating\_degree\_days:heatpump\_type & 2.86\\
heating\_degree\_days:building\_type & 61.44\\
\bottomrule
\end{longtabu}

Most predictors have VIF below 3, indicating no problematic
multicollinearity. The exception is \texttt{heating\_degree\_days} (VIF
= 61.55) and its interaction with \texttt{building\_typehouse} (VIF =
61.44). These elevated values are expected for interaction terms and do
not invalidate the model or inflate coefficient uncertainty.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:lm-model-comparison}LM model comparison — Adj. R² on full data; MAE from 5-fold CV}\\
\toprule
Model & Adj. R² & CV MAE (kWh/day)\\
\midrule
Simple MLR (main effects) & 0.2727 & 10.97\\
Extended MLR (+ interactions) & 0.2743 & 10.96\\
\bottomrule
\end{longtabu}

The simple model achieves an adjusted R² of 0.2727. Adding the two
interaction terms improves this to 0.2743, a real but modest gain.
Five-fold CV MAE is roughly 11 kWh/day for the extended model. The
interaction terms are meaningful, but overall explanatory power remains
limited on this dataset.

\subsubsection{Key Findings}\label{key-findings}

\textbf{Heating degree days is the dominant weather driver:} Cold
weather is the primary positive predictor of energy consumption. The
interaction term (β = 0.039, p \textless{} 0.001) shows that houses are
more sensitive to cold than flats, consistent with lower thermal
efficiency.

\textbf{Household size has the strongest marginal effect:} With β =
0.134, each additional resident increases daily consumption by
\textasciitilde14.3\%, making it the largest single-predictor effect in
the model after the building type interaction.

\textbf{Houses consume substantially more, especially in winter:} Both
the baseline offset (β = 0.220, house vs.~flat) and the temperature
interaction (β = 0.039) point the same way: houses start higher and get
more sensitive to cold as temperatures drop.

\textbf{Ground-source heat pumps are more efficient and more stable:}
They consume \textasciitilde13.3\% less at baseline and respond less to
temperature swings (interaction β = −0.003), consistent with the
efficiency advantage of ground-source systems at low outdoor
temperatures.

\textbf{Humidity is not a useful predictor:} \texttt{humidity\_avg} is
not significant (p = 0.165) once the other weather variables are
controlled for.

\textbf{Overall explanatory power is limited:} The extended model
explains \textasciitilde27.4\% of the variance in log daily consumption
(adj. R² = 0.2743). On the original kWh scale, mean absolute error is 11
kWh/day (5-fold CV).

\subsubsection{Conclusion}\label{conclusion}

The linear model identifies the main structural and weather-related
drivers of daily household energy consumption. All predictors except
humidity are significant, and the interaction terms show that cold
weather affects houses and ground-source pump households differently.

However, the model has \textbf{limited predictive value}. An adjusted R²
of 0.27 leaves \textasciitilde73\% of the variance unexplained. At the
household-day level, predictions are too imprecise for operational use.
Household-level heterogeneity is likely the cause: baseline consumption
varies substantially across households in ways a cross-sectional model
cannot capture.

For inference, the model does its job: it gives directly interpretable
coefficient estimates for every predictor. For forecasting, models with
household-level random effects would be needed.

\subsection{GLM -- Poisson}\label{glm-poisson}

\emph{Lead: Raphaël Spagolla}

\subsubsection{Objective}\label{objective-1}

The aim of this analysis is to model the number of high-consumption days
per household-month (\(n_{high\ days}\)). This variable represents count
data, taking non-negative integer values. A plain linear model is not
appropriate here, as it assumes normally distributed errors and can
produce negative predictions --- both of which are incompatible with
count outcomes.

A Poisson Generalised Linear Model (GLM) is used instead, as it is
specifically designed for non-negative integer outcomes and naturally
allows the variance to grow with the mean. By including an offset for
the number of observed days, the model estimates rates, allowing
interpretation of results in terms of relative changes (rate ratios).

\subsubsection{Model Setup}\label{model-setup-1}

\begin{verbatim}
## n_high_days ~ heating_degree_days + temp_avg + living_area + 
##     building_type + heatpump_type + has_floor_heating + n_residents + 
##     share_weekend
\end{verbatim}

The response variable is the number of high-consumption days per
household-month (\(n_{high\ days}\)). A day is classified as a
high-consumption day if its daily \texttt{log\_kWh\_total} exceeds that
household's own 75th percentile, consistent with the threshold used in
the GLM Binomial and throughout the report. Because the number of
observed days can vary slightly across household--months, the model
includes the logarithm of the observed days \((\log(n_{days}))\) as an
offset. This adjustment effectively converts the outcome into a rate ---
high-consumption days per observed day --- so that observations remain
comparable even when exposure differs between months.

To model these rates, a Poisson GLM with a log-link is fitted:

\[
\log(\mathbb{E}[Y_i]) = \beta_0 + \beta_1 X_{1i} + \cdots + \beta_p X_{pi} + \log(n\_days_i)
\]

The log-link guarantees positive fitted values and supports a
multiplicative interpretation of effects.

One predictor warrants clarification: \texttt{share\_weekend} is the
monthly proportion of weekend days within a household--month (a
continuous value between 0 and 1), and is distinct from the daily binary
\texttt{is\_weekend} flag used in the GLM Binomial and other daily-level
models.

\subsubsection{Model Results}\label{model-results-1}

The results are interpreted in terms of \emph{percentage changes in the
expected rate}, holding all other variables constant.

\textbf{Building type (house vs flat):} Households living in houses have
a rate of high-consumption days approximately 363\% higher than those
living in flats \(((4.632 - 1) \times 100\%)\). This is by far the
strongest effect in the model, clearly visible in the boxplot, and
indicates that building type is the dominant structural driver of
consumption patterns.

\textbf{Average temperature:} The rate ratio of 0.915 implies that each
additional degree Celsius is associated with an 8.5\% decrease in the
expected rate of high- consumption days \(((1 - 0.915) \times 100\%)\).
This reflects reduced heating needs at warmer temperatures, consistent
with the strong negative trend visible in the scatterplot.

\textbf{Heating degree days:} The rate ratio is marginally below 1
(\(\approx\) 0.999) and not statistically significant. Once average
temperature is already in the model, heating degree days add little
additional explanatory power, as both variables capture overlapping
thermal information. This collinearity explains why the coefficient is
effectively zero.

\textbf{Number of residents:} Each additional household member increases
the expected rate by approximately 8.9\% \(((1.089 - 1) \times 100\%)\).
This reflects the intuitive result that larger households consume more
energy overall.

\textbf{Living area:} The rate ratio of 1.001 indicates a statistically
significant but practically small positive effect --- each additional
square metre increases the expected rate by about 0.1\%. The effect
accumulates for larger dwellings but remains modest compared to building
type or household size.

\textbf{Ground-source heat pump:} Households equipped with a
ground-source heat pump show a rate approximately 9.3\% lower than the
reference heat pump type \(((1 -
0.907) \times 100\%)\). This is consistent with ground-source systems
being more energy-efficient, particularly during colder periods.

\textbf{Floor heating:} Households with floor heating show a rate
approximately 13\% higher than those without
\(((1.130 - 1) \times 100\%)\). This likely reflects the greater energy
input required by radiant floor systems to maintain comfort
temperatures.

\textbf{Weekend share:} This predictor has a very wide confidence
interval and is non-significant once overdispersion is accounted for
(quasi-Poisson p \textgreater{} 0.05). The direction of the raw Poisson
estimate should not be interpreted. The two models are not directly
comparable on this predictor, as they operate at different aggregation
levels.

Overall, structural and household characteristics (building type, size,
and number of residents) exhibit the strongest and most reliable
effects, while temperature captures an important environmental
influence.

\subsubsection{Visual Evidence}\label{visual-evidence-1}

To complement the model output, the plots below provide direct visual
support for the main relationships in the data.

The \emph{boxplot by building type} shows a striking separation between
flats and houses. Flats cluster tightly with a median close to 3
high-consumption days and only two mild outliers, while houses display a
median around 16 days with a very wide interquartile range extending
from nearly 0 to 28. This large difference in both level and spread
confirms that building type is the dominant predictor in the model.

The \emph{scatterplot of high-consumption days versus average
temperature} reveals a strong and consistent negative pattern. At
temperatures near 0°C, many households record close to 30
high-consumption days, whereas above 15°C the counts concentrate near
zero. The smooth LOESS curve decreases steeply in the 0--10°C range and
flattens at higher temperatures, suggesting diminishing marginal effects
of warmth once heating demand is already low.

\includegraphics[width=0.5\linewidth]{report_files/figure-latex/glm-poisson-plots-1}
\includegraphics[width=0.5\linewidth]{report_files/figure-latex/glm-poisson-plots-2}

The \emph{rate-ratio plot} below summarises all model effects on a log
scale. \emph{House (vs flat)} stands far to the right of the reference
line (RR \(\approx\) 4.6), confirming it as the dominant effect.
\emph{Weekend share} lies furthest to the left but with a very wide CI
crossing 1, indicating high uncertainty. \emph{Temperature} and
\emph{ground-source heat pump} show clear reductions (RR \textless{} 1),
while \emph{floor heating}, \emph{number of residents}, and \emph{living
area} show moderate to small increases. \emph{Heating degree days} sits
right at 1 and is the only non-significant predictor (shown in grey).

\begin{center}\includegraphics{report_files/figure-latex/glm-poisson-rr-plot-1} \end{center}

\subsubsection{Model Diagnostics}\label{model-diagnostics-1}

A key assumption of the Poisson GLM is \emph{equidispersion}, i.e., that
the conditional variance equals the conditional mean. We assess this by
comparing the residual deviance to the residual degrees of freedom. For
the fitted Poisson model, the residual deviance is 27,529.6 on 3291 df,
yielding a ratio of 8.37. Since this substantially exceeds 1, there is
strong evidence of \emph{overdispersion} --- the Poisson model
underestimates standard errors and overstates statistical significance.

We therefore refit the model using a \emph{quasi-Poisson} family, which
retains identical point estimates but inflates standard errors by
\(\sqrt{\hat{\phi}}\) (\(\hat{\phi}\) = 7.74), yielding more
conservative and reliable inference. The most visible consequence is
that \emph{weekend share} shifts from significant under Poisson (p =
0.028) to clearly non-significant under quasi-Poisson (p = 0.43),
indicating that this effect should not be over-interpreted.

The table and plot below show the SE inflation across all predictors.
The effect is proportional --- predictors with larger SEs to begin with
(e.g., \emph{weekend share}, \emph{house vs flat}) show the largest
absolute increase, while those with very small SEs (e.g., \emph{living
area}, \emph{number of residents}) are inflated by a smaller absolute
amount but the same factor \(\sqrt{\hat{\phi}}\).

\begin{center}\includegraphics{report_files/figure-latex/quasi-se-plot-1} \end{center}

\subsubsection{Goodness of Fit}\label{goodness-of-fit}

To assess predictive accuracy, we compare fitted values against observed
counts and report the Root Mean Squared Error (RMSE). The
observed-vs-fitted plot is rendered as a hexbin to handle overplotting
given the large number of observations.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X}
\caption{\label{tab:goodness-of-fit}Root Mean Squared Error for the Poisson model.}\\
\toprule
Model & RMSE\\
\midrule
Poisson & 9.452\\
\bottomrule
\end{longtabu}

The RMSE of 9.452 days reflects substantial residual spread, partly
explained by the high overdispersion (\(\hat{\phi}\) = 7.74). Note that
the quasi-Poisson model produces identical fitted values and therefore
the same RMSE, as it only affects standard errors and inference, not
point predictions.

\subsubsection{Conclusion}\label{conclusion-1}

The Poisson GLM provides a clear and interpretable account of the
factors driving the frequency of high-consumption days. Building type,
temperature, and household size emerge as the strongest and most robust
predictors, consistent with both domain knowledge and the exploratory
analysis.

However, a dispersion ratio of 8.37 confirms substantial overdispersion,
making standard Poisson inference unreliable. The quasi-Poisson model
corrects for this by inflating standard errors appropriately, leading to
more conservative and trustworthy conclusions --- most notably, the loss
of significance for weekend share.

While the quasi-Poisson model improves inference, a negative binomial
model could be considered as a more flexible alternative, as it models
the overdispersion through an explicit distributional parameter rather
than a post- hoc correction.

\subsection{GLM -- Binomial}\label{glm-binomial}

\emph{Lead: Emanuel Lemma}

\subsubsection{Objective}\label{objective-2}

Can we predict whether a given day will be unusually high-consumption
for a specific household? This section fits a \textbf{Generalised Linear
Model with a binomial family} to answer exactly that question. The
response variable \texttt{high\_consumption} is a binary indicator that
equals 1 if the household's daily \texttt{log\_kWh\_total} exceeds that
household's own 75th percentile and 0 otherwise. Using a per-household
threshold means the model is not distinguishing houses from flats. Each
household's own consumption baseline is already accounted for. Instead,
the model learns what drives a day to be in the top 25\% for a given
household, regardless of its size or type. By modelling the log-odds of
high consumption as a linear function of weather conditions, building
characteristics, and calendar effects, we obtain a model that is both
interpretable and actionable for a client interested in understanding
what drives demand spikes at the household level.

\subsubsection{Model Setup}\label{model-setup-2}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}

\NormalTok{hh\_q75 }\OtherTok{\textless{}{-}}\NormalTok{ heapo }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(Household\_ID) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{hh\_q75 =} \FunctionTok{quantile}\NormalTok{(log\_kWh\_total, }\FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{df\_glm }\OtherTok{\textless{}{-}}\NormalTok{ heapo }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{left\_join}\NormalTok{(hh\_q75, }\AttributeTok{by =} \StringTok{"Household\_ID"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{high\_consumption =} \FunctionTok{as.integer}\NormalTok{(log\_kWh\_total }\SpecialCharTok{\textgreater{}=}\NormalTok{ hh\_q75),}
    \AttributeTok{month =} \FunctionTok{as.factor}\NormalTok{(month)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}
\NormalTok{    high\_consumption,}
\NormalTok{    heating\_degree\_days,}
\NormalTok{    temp\_avg,}
\NormalTok{    living\_area,}
\NormalTok{    building\_type,}
\NormalTok{    heatpump\_type,}
\NormalTok{    has\_floor\_heating,}
\NormalTok{    n\_residents,}
\NormalTok{    is\_weekend,}
\NormalTok{    month}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{drop\_na}\NormalTok{()}

\NormalTok{train\_idx }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(df\_glm), }\FloatTok{0.8} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(df\_glm))}
\NormalTok{train\_df }\OtherTok{\textless{}{-}}\NormalTok{ df\_glm[train\_idx, ]}
\NormalTok{test\_df }\OtherTok{\textless{}{-}}\NormalTok{ df\_glm[}\SpecialCharTok{{-}}\NormalTok{train\_idx, ]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{file.exists}\NormalTok{(}\StringTok{"../models/glm\_binomial/glm\_binomial\_hh\_q75.rds"}\NormalTok{)) \{}
\NormalTok{  model\_glm }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(high\_consumption }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_df, }\AttributeTok{family =}\NormalTok{ binomial)}
  \FunctionTok{saveRDS}\NormalTok{(model\_glm, }\StringTok{"../models/glm\_binomial/glm\_binomial\_hh\_q75.rds"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  model\_glm }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"../models/glm\_binomial/glm\_binomial\_hh\_q75.rds"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

For each of the 127 households, the 75th percentile of their
\texttt{log\_kWh\_total} is computed and used as that household's
personal high-consumption threshold. A day is labelled 1 if it falls in
the top 25\% of that household's own consumption distribution. By
construction, every household contributes exactly 25\% high-consumption
days, so building type and household size are absorbed into the
threshold and do not mechanically drive the outcome. The dataset is
restricted to nine predictors covering weather conditions, building
characteristics, and calendar effects, then split into 80\% training and
20\% test sets. The model is fitted with \texttt{glm()} using
\texttt{family\ =\ binomial}, which models the log-odds of high
consumption as a linear combination of predictors. The saved model is
reloaded on subsequent knits to avoid refitting.

\subsubsection{Model Results}\label{model-results-2}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_prob }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_glm, }\AttributeTok{newdata =}\NormalTok{ test\_df, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred\_class }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(pred\_prob }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\DataTypeTok{L}\NormalTok{, }\DecValTok{0}\DataTypeTok{L}\NormalTok{)}
\NormalTok{actual }\OtherTok{\textless{}{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{high\_consumption}

\NormalTok{conf\_mat }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\AttributeTok{Predicted =}\NormalTok{ pred\_class, }\AttributeTok{Actual =}\NormalTok{ actual)}
\NormalTok{accuracy }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(pred\_class }\SpecialCharTok{==}\NormalTok{ actual)}

\NormalTok{compute\_auc }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(actual, prob) \{}
\NormalTok{  ord }\OtherTok{\textless{}{-}} \FunctionTok{order}\NormalTok{(prob, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  act }\OtherTok{\textless{}{-}}\NormalTok{ actual[ord]}
\NormalTok{  n1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{  n0 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}
\NormalTok{  tpr }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{cumsum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ n1)}
\NormalTok{  fpr }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{cumsum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ n0)}
  \FunctionTok{sum}\NormalTok{(}\FunctionTok{diff}\NormalTok{(fpr) }\SpecialCharTok{*}\NormalTok{ (tpr[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ tpr[}\SpecialCharTok{{-}}\FunctionTok{length}\NormalTok{(tpr)]) }\SpecialCharTok{/} \DecValTok{2}\NormalTok{)}
\NormalTok{\}}

\NormalTok{glm\_auc\_val }\OtherTok{\textless{}{-}} \FunctionTok{compute\_auc}\NormalTok{(actual, pred\_prob)}
\NormalTok{tp }\OtherTok{\textless{}{-}}\NormalTok{ conf\_mat[}\StringTok{"1"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{tn }\OtherTok{\textless{}{-}}\NormalTok{ conf\_mat[}\StringTok{"0"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}
\NormalTok{fp }\OtherTok{\textless{}{-}}\NormalTok{ conf\_mat[}\StringTok{"1"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}
\NormalTok{fn }\OtherTok{\textless{}{-}}\NormalTok{ conf\_mat[}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{precision }\OtherTok{\textless{}{-}}\NormalTok{ tp }\SpecialCharTok{/}\NormalTok{ (tp }\SpecialCharTok{+}\NormalTok{ fp)}
\NormalTok{recall }\OtherTok{\textless{}{-}}\NormalTok{ tp }\SpecialCharTok{/}\NormalTok{ (tp }\SpecialCharTok{+}\NormalTok{ fn)}
\NormalTok{f1 }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ precision }\SpecialCharTok{*}\NormalTok{ recall }\SpecialCharTok{/}\NormalTok{ (precision }\SpecialCharTok{+}\NormalTok{ recall)}
\NormalTok{specificity }\OtherTok{\textless{}{-}}\NormalTok{ tn }\SpecialCharTok{/}\NormalTok{ (tn }\SpecialCharTok{+}\NormalTok{ fp)}
\end{Highlighting}
\end{Shaded}

Coefficients from a binomial GLM are expressed as \textbf{odds ratios}
(OR = exp(coefficient)). A value above 1 increases the odds that a day
falls in the top 25\% of a household's own consumption, and a value
below 1 decreases it, relative to the reference category.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:glm-binomial-coef-table}GLM Binomial: coefficient estimates and odds ratios. Month dummies omitted here. All effects shown in the OR plot below.}\\
\toprule
Term & Estimate & OR & CI Low & CI High & p-value\\
\midrule
is\_weekend & 0.452 & 1.571 & 1.500 & 1.645 & 0.000\\
temp\_avg & -0.194 & 0.823 & 0.808 & 0.840 & 0.000\\
heating\_degree\_days & 0.062 & 1.064 & 1.045 & 1.084 & 0.000\\
has\_floor\_heating & -0.047 & 0.955 & 0.904 & 1.008 & 0.096\\
heatpump\_typeground-source & 0.023 & 1.024 & 0.980 & 1.069 & 0.292\\
\addlinespace
building\_typehouse & -0.022 & 0.978 & 0.822 & 1.164 & 0.803\\
n\_residents & 0.008 & 1.008 & 0.988 & 1.027 & 0.441\\
living\_area & 0.000 & 1.000 & 1.000 & 1.000 & 0.765\\
\bottomrule
\end{longtabu}

A striking result of using the per-household threshold is that
structural predictors (building type, heat pump type, living area, and
number of residents) are all statistically non-significant. This is
expected because the threshold is set individually for each household,
and these characteristics are already accounted for in the baseline. The
model is therefore answering a different and more useful question. Given
how this household normally behaves, what makes a specific day unusually
high?

The coefficient table reveals several key patterns.

\begin{itemize}
\tightlist
\item
  \textbf{Weekend:} The dominant predictor, with OR = 1.57. Days falling
  on a Saturday or Sunday have 57\% higher odds of being a top-25\%
  consumption day for that household. Households spend more time at home
  on weekends, increasing both heating and appliance usage regardless of
  building type or size.
\item
  \textbf{Average temperature:} Each additional degree Celsius reduces
  the odds by 17.7\% (OR = 0.823, p \textless{} 0.001). Colder days push
  households above their own typical usage level through increased heat
  pump operation.
\item
  \textbf{Heating degree days:} Each additional HDD increases the odds
  by 6.4\% (OR = 1.064, p \textless{} 0.001). HDD and temperature are
  collinear and together capture the thermal load on the heat pump. Both
  are retained because HDD captures heating demand only and is zero on
  warm days, while temp\_avg can detect cooling demand from reversible
  heat pumps, a pattern HDD alone would miss entirely.
\item
  \textbf{Building type, heat pump type, living area, number of
  residents, floor heating:} None of these are statistically significant
  (all p \textgreater{} 0.05). Once the model conditions on a
  household's own 75th percentile, these structural characteristics
  carry no additional explanatory power for day-to-day variation in
  consumption.
\item
  \textbf{Month:} Spring and autumn show the strongest reductions
  relative to January. April and October have the lowest odds (OR 0.29
  and 0.28 respectively), as these are transition months when neither
  heating nor cooling is needed. Notably, June and July are not
  significantly different from January (p = 0.31 and 0.09), suggesting
  that some households also produce high-consumption days in summer,
  likely from heat pump cooling or increased hot water use. December is
  likewise indistinguishable from January (p = 0.41). The full seasonal
  pattern is visible in the odds ratio plot below.
\end{itemize}

\subsubsection{Visual Evidence}\label{visual-evidence-2}

Each point shows the estimated odds ratio for one predictor, with 95\%
confidence intervals. Points to the right of the dashed line (OR
\textgreater{} 1) increase the odds of high consumption, and points to
the left decrease them. Blue points are statistically significant (p
\textless{} 0.05) and grey points are not. The log scale ensures that
effects of equal magnitude in both directions appear symmetrically.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_summary }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(model\_glm))}
\NormalTok{coef\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{term =} \FunctionTok{rownames}\NormalTok{(coef\_summary),}
  \AttributeTok{estimate =}\NormalTok{ coef\_summary[, }\StringTok{"Estimate"}\NormalTok{],}
  \AttributeTok{se =}\NormalTok{ coef\_summary[, }\StringTok{"Std. Error"}\NormalTok{],}
  \AttributeTok{p\_value =}\NormalTok{ coef\_summary[, }\StringTok{"Pr(\textgreater{}|z|)"}\NormalTok{]}
\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(term }\SpecialCharTok{!=} \StringTok{"(Intercept)"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{odds\_ratio =} \FunctionTok{exp}\NormalTok{(estimate),}
    \AttributeTok{ci\_low =} \FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se),}
    \AttributeTok{ci\_high =} \FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se),}
    \AttributeTok{significant =}\NormalTok{ p\_value }\SpecialCharTok{\textless{}} \FloatTok{0.05}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(odds\_ratio)}

\FunctionTok{ggplot}\NormalTok{(}
\NormalTok{  coef\_df,}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ odds\_ratio, }\AttributeTok{y =} \FunctionTok{reorder}\NormalTok{(term, odds\_ratio), }\AttributeTok{color =}\NormalTok{ significant)}
\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \FloatTok{2.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_errorbarh}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xmin =}\NormalTok{ ci\_low, }\AttributeTok{xmax =}\NormalTok{ ci\_high), }\AttributeTok{height =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{1}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_neutral) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"FALSE"} \OtherTok{=}\NormalTok{ clr\_neutral, }\StringTok{"TRUE"} \OtherTok{=}\NormalTok{ clr\_primary),}
    \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"n.s."}\NormalTok{, }\StringTok{"p \textless{} 0.05"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_log10}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GLM Binomial – Odds Ratios with 95\% CIs"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Odds Ratio (log scale)"}\NormalTok{,}
    \AttributeTok{y =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{color =} \ConstantTok{NULL}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/glm-binomial-or-1} \end{center}

The wide spread of odds ratios shows that calendar effects, particularly
month dummies, drive the largest deviations from OR = 1, while
structural household characteristics (building type, heat pump type)
cluster near the reference line and are statistically non-significant,
as expected by the modell setup.

The ROC curve traces the model's sensitivity against its false positive
rate as the classification threshold varies from 0 to 1. The dashed
diagonal represents a model that predicts at random (AUC = 0.5). The
further the blue curve bows toward the top-left corner, the better the
model separates the two classes regardless of threshold choice.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{roc\_df }\OtherTok{\textless{}{-}}\NormalTok{ (}\ControlFlowTok{function}\NormalTok{(actual, prob) \{}
\NormalTok{  ord }\OtherTok{\textless{}{-}} \FunctionTok{order}\NormalTok{(prob, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  act }\OtherTok{\textless{}{-}}\NormalTok{ actual[ord]}
\NormalTok{  n1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{  n0 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}
  \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{fpr =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{cumsum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ n0),}
    \AttributeTok{tpr =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{cumsum}\NormalTok{(act }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ n1)}
\NormalTok{  )}
\NormalTok{\})(actual, pred\_prob)}

\FunctionTok{ggplot}\NormalTok{(roc\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ fpr, }\AttributeTok{y =}\NormalTok{ tpr)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =}\NormalTok{ clr\_primary, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_neutral) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GLM Binomial – ROC Curve"}\NormalTok{,}
    \AttributeTok{subtitle =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"AUC = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(glm\_auc\_val, }\DecValTok{3}\NormalTok{)),}
    \AttributeTok{x =} \StringTok{"False Positive Rate"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"True Positive Rate"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/glm-binomial-roc-1} \end{center}

With an AUC of 0.896, the model correctly ranks a randomly drawn
high-consumption day above a randomly drawn low-consumption day 89.6\%
of the time, which is a meaningful improvement over chance.

\subsubsection{Model Diagnostics}\label{model-diagnostics-2}

The confusion matrix shows the model's classifications on the held-out
test set. The model correctly identifies 63.5\% of true high-
consumption days (sensitivity) and 92.6\% of true low-consumption days
(specificity). Because the per-household 75th percentile produces a
75/25 class split, a naive classifier that always predicts normal would
achieve around 74.7\% accuracy. The model's accuracy of 85.2\% is only
10.5 percentage points above this baseline, so AUC is the more
informative metric.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conf\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Predicted =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{, }\StringTok{"1"}\NormalTok{), }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{, }\StringTok{"0"}\NormalTok{)),}
  \AttributeTok{Actual =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{), }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{)),}
  \AttributeTok{Count =} \FunctionTok{c}\NormalTok{(tn, fn, fp, tp),}
  \AttributeTok{Label =} \FunctionTok{c}\NormalTok{(}\StringTok{"TN"}\NormalTok{, }\StringTok{"FN"}\NormalTok{, }\StringTok{"FP"}\NormalTok{, }\StringTok{"TP"}\NormalTok{)}
\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(conf\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Actual, }\AttributeTok{y =}\NormalTok{ Predicted, }\AttributeTok{fill =}\NormalTok{ Label)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(Label, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, Count)),}
    \AttributeTok{size =} \DecValTok{5}\NormalTok{,}
    \AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"white"}
\NormalTok{  ) }\SpecialCharTok{+}
\FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"TN"} \OtherTok{=}\NormalTok{ clr\_primary, }\StringTok{"TP"} \OtherTok{=}\NormalTok{ clr\_primary,}
                             \StringTok{"FP"} \OtherTok{=}\NormalTok{ clr\_secondary, }\StringTok{"FN"} \OtherTok{=}\NormalTok{ clr\_secondary)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_discrete}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"} \OtherTok{=} \StringTok{"Low (0)"}\NormalTok{, }\StringTok{"1"} \OtherTok{=} \StringTok{"High (1)"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_discrete}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"} \OtherTok{=} \StringTok{"Low (0)"}\NormalTok{, }\StringTok{"1"} \OtherTok{=} \StringTok{"High (1)"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GLM Binomial – Confusion Matrix"}\NormalTok{,}
    \AttributeTok{subtitle =} \FunctionTok{paste0}\NormalTok{(}
      \StringTok{"Accuracy = "}\NormalTok{,}
      \FunctionTok{round}\NormalTok{(accuracy, }\DecValTok{3}\NormalTok{),}
      \StringTok{"  |  F1 = "}\NormalTok{,}
      \FunctionTok{round}\NormalTok{(f1, }\DecValTok{3}\NormalTok{),}
      \StringTok{"  |  AUC = "}\NormalTok{,}
      \FunctionTok{round}\NormalTok{(glm\_auc\_val, }\DecValTok{3}\NormalTok{)}
\NormalTok{    ),}
    \AttributeTok{x =} \StringTok{"Actual class"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Predicted class"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Count"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\AttributeTok{panel.grid =} \FunctionTok{element\_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/glm-binomial-confmat-1} \end{center}

The remaining errors occur mainly on days where consumption is only
marginally above or below the household's personal threshold and
therefore genuinely ambiguous. The F1 score of 0.685 summarises the
balance between precision and recall into a single number, useful here
because the 75/25 class split means accuracy alone is misleading. The
AUC of 0.896 measures the model's ability to rank a randomly drawn
high-consumption day above a randomly drawn low-consumption day,
regardless of the classification threshold chosen. Together, F1 and AUC
confirm that the model performs well beyond what the modest accuracy
gain over the naive baseline suggests.

\subsubsection{Key Findings}\label{key-findings-1}

\begin{itemize}
\tightlist
\item
  The model achieves an AUC of 0.896 and an accuracy of 85.2\% on the
  held-out test set, compared to a naive baseline of 74.7\%. AUC is the
  more informative metric given the 75/25 class split.
\item
  \textbf{Weekend is the dominant predictor} (OR = 1.57). Occupancy
  patterns, not structural characteristics, are the strongest driver of
  within-household demand spikes.
\item
  \textbf{Building type, heat pump type, living area, floor heating, and
  number of residents are all non-significant.} The per-household
  threshold neutralises these structural differences. The model is
  explaining day-to-day variation around each household's own baseline,
  not variation between households.
\item
  \textbf{Cold weather drives high-consumption days} through both the
  temperature coefficient (OR = 0.823 per °C) and HDD (OR = 1.064 per
  HDD).
\item
  \textbf{Spring and autumn are low-risk seasons.} April and October
  show the largest reductions relative to January. June and July are not
  significantly different from January, indicating that some households
  generate high-consumption days in summer as well, likely from cooling
  or increased hot water use.
\item
  \textbf{Sensitivity of 63.5\%} means the model correctly flags roughly
  two thirds of actual high-consumption days but also misses one in
  three demand spikes entirely. A client using this model for
  operational alerting should be aware of this limitation.
\end{itemize}

\subsubsection{Conclusion}\label{conclusion-2}

The GLM Binomial achieves an AUC of 0.896 and a sensitivity of 63.5\%
using a per-household 75th percentile threshold. The sensitivity of
63.5\% is a known limitation, one in three high-consumption days goes
undetected, which should be weighed against the strong AUC of 0.896 when
deciding whether this model is sufficient for operational use. The most
important finding is that structural household characteristics (building
type, heat pump type, size, and number of residents) become
non-significant once the model conditions on each household's own
baseline. Day-to-day variation in consumption is driven primarily by
weekend occupancy and cold weather, not by what kind of building or heat
pump a household has.

For the client, this means that demand spikes at the household level are
predictable from calendar and weather information alone, without needing
to know anything about the household's physical characteristics. The
model is transparent, interpretable, and provides a well-founded
baseline for comparison with more flexible classification methods.

\subsection{Generalised Additive Model (GAM)}\label{gam}

\emph{Lead: Emanuel Lemma}

\subsubsection{Objective}\label{objective-3}

The Linear Model assumes that each predictor affects the response in a
straight line. For energy consumption, this is often too rigid. The
relationship between heating demand and electricity use may differ
between houses and flats, and between heat pump types, in ways that
cannot be captured by fixed linear slopes. A \textbf{Generalised
Additive Model (GAM)} relaxes this assumption by replacing fixed slopes
with flexible smooth functions, while remaining fully interpretable
through its component plots. Here we model \texttt{log\_kWh\_total}
using \textbf{exactly the same predictors as the extended Linear Model},
namely heating degree days (interacted with building type and heat pump
type), sunshine hours, humidity, living area, and the number of
residents. The GAM replaces the LM's explicit interaction terms with
\texttt{by\ =} smooths, which allow the shape of the heating-demand
curve to vary freely between groups. This makes the comparison between
the two models direct and fair.

\subsubsection{Model Setup}\label{model-setup-3}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_gam }\OtherTok{\textless{}{-}}\NormalTok{ heapo }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}
\NormalTok{    log\_kWh\_total,}
\NormalTok{    heating\_degree\_days,}
\NormalTok{    sunshine\_hours,}
\NormalTok{    humidity\_avg,}
\NormalTok{    living\_area,}
\NormalTok{    building\_type,}
\NormalTok{    heatpump\_type,}
\NormalTok{    n\_residents}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{drop\_na}\NormalTok{()}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}
\NormalTok{gam\_train\_idx }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(df\_gam), }\FloatTok{0.8} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(df\_gam))}
\NormalTok{gam\_train }\OtherTok{\textless{}{-}}\NormalTok{ df\_gam[gam\_train\_idx, ]}
\NormalTok{gam\_test }\OtherTok{\textless{}{-}}\NormalTok{ df\_gam[}\SpecialCharTok{{-}}\NormalTok{gam\_train\_idx, ]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{file.exists}\NormalTok{(}\StringTok{"../models/gam/gam\_model\_v2.rds"}\NormalTok{)) \{}
\NormalTok{  model\_gam }\OtherTok{\textless{}{-}}\NormalTok{ mgcv}\SpecialCharTok{::}\FunctionTok{gam}\NormalTok{(}
\NormalTok{    log\_kWh\_total }\SpecialCharTok{\textasciitilde{}}
      \FunctionTok{s}\NormalTok{(heating\_degree\_days, }\AttributeTok{by =}\NormalTok{ building\_type) }\SpecialCharTok{+}
      \FunctionTok{s}\NormalTok{(heating\_degree\_days, }\AttributeTok{by =}\NormalTok{ heatpump\_type) }\SpecialCharTok{+}
\NormalTok{      building\_type }\SpecialCharTok{+}
\NormalTok{      heatpump\_type }\SpecialCharTok{+}
      \FunctionTok{s}\NormalTok{(sunshine\_hours) }\SpecialCharTok{+}
      \FunctionTok{s}\NormalTok{(humidity\_avg) }\SpecialCharTok{+}
      \FunctionTok{s}\NormalTok{(living\_area) }\SpecialCharTok{+}
\NormalTok{      n\_residents,}
    \AttributeTok{family =}\NormalTok{ gaussian,}
    \AttributeTok{data =}\NormalTok{ gam\_train}
\NormalTok{  )}
  \FunctionTok{saveRDS}\NormalTok{(model\_gam, }\StringTok{"../models/gam/gam\_model\_v2.rds"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  model\_gam }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"../models/gam/gam\_model\_v2.rds"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

The model uses \texttt{by\ =} smooths for heating degree days, which
allow the heating- demand curve to take a completely different shape for
each building type and heat pump type, equivalent to the interaction
terms in the extended LM but without constraining the relationship to be
linear. All smooths are penalised regression splines with automatic
smoothness selection via restricted maximum likelihood.

\begin{align}
\log(\text{kWh}_i) = \; & \alpha + \beta_1 \text{building type}_i + \beta_2 \text{heatpump type}_i + \beta_3 \text{n residents}_i \\
& + s(\text{HDD}_i \mid \text{building type}_i) + s(\text{HDD}_i \mid \text{heatpump type}_i) \\
& + s(\text{sunshine hours}_i) + s(\text{humidity avg}_i) + s(\text{living area}_i) + \epsilon_i
\end{align}

where \(s(\cdot)\) denotes penalised regression splines with automatic
smoothness selection via Restricted Maximum Likelihood (REML), which
balances fit and smoothness automatically, and the \(by =\) smooths
allow the shape of the heating-demand curve to vary freely between
groups rather than constraining it to a fixed linear slope.

\subsubsection{Model Results}\label{model-results-3}

The table below summarises the estimated degrees of freedom, F-statistic
and significance for each smooth term in the model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s\_gam }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(model\_gam)}
\NormalTok{s\_tab }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(s\_gam}\SpecialCharTok{$}\NormalTok{s.table)}
\NormalTok{s\_tab }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}\AttributeTok{Term =} \FunctionTok{rownames}\NormalTok{(s\_tab), s\_tab)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{Term =}\NormalTok{ s\_tab}\SpecialCharTok{$}\NormalTok{Term,}
    \AttributeTok{EDF =} \FunctionTok{round}\NormalTok{(s\_tab}\SpecialCharTok{$}\NormalTok{edf, }\DecValTok{1}\NormalTok{),}
    \AttributeTok{F =} \FunctionTok{round}\NormalTok{(s\_tab}\SpecialCharTok{$}\NormalTok{F, }\DecValTok{2}\NormalTok{),}
    \AttributeTok{p.value =} \FunctionTok{formatC}\NormalTok{(s\_tab[[}\StringTok{"p{-}value"}\NormalTok{]], }\AttributeTok{digits =} \DecValTok{3}\NormalTok{, }\AttributeTok{format =} \StringTok{"g"}\NormalTok{)}
\NormalTok{  ),}
  \AttributeTok{caption =} \StringTok{"GAM – Smooth Terms"}\NormalTok{,}
  \AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Smooth Term"}\NormalTok{, }\StringTok{"EDF"}\NormalTok{, }\StringTok{"F"}\NormalTok{, }\StringTok{"p{-}value"}\NormalTok{),}
  \AttributeTok{row.names =} \ConstantTok{FALSE}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedright}X}
\caption{\label{tab:gam-smooth-table}GAM – Smooth Terms}\\
\toprule
Smooth Term & EDF & F & p-value\\
\midrule
s(heating\_degree\_days):building\_typeappartment & 0.8 & 1.34 & 0.316\\
s(heating\_degree\_days):building\_typehouse & 5.3 & 26.79 & 0\\
s(heating\_degree\_days):heatpump\_typeair-source & 1.7 & 10.64 & 1.38e-05\\
s(heating\_degree\_days):heatpump\_typeground-source & 1.3 & 5.43 & 0.00523\\
s(sunshine\_hours) & 6.5 & 34.95 & 0\\
\addlinespace
s(humidity\_avg) & 5.3 & 1.69 & 0.118\\
s(living\_area) & 9.0 & 417.39 & 0\\
\bottomrule
\end{longtabu}

The smooth terms reveal where non-linearity is present in the data.

\begin{itemize}
\tightlist
\item
  \textbf{s(HDD):flat (edf = 0.8):} The smooth shows a mild positive
  trend but with a very wide confidence band, reflecting high
  uncertainty. The non-significance (p = 0.316) is due to this
  uncertainty rather than the effect being absent. For flats, colder
  days are associated with higher consumption but the uncertainty is too
  large to pin down the exact shape of this relationship. This likely
  reflects higher variability in flat consumption patterns rather than
  the absence of a heating effect.
\item
  \textbf{s(HDD):house (edf = 5.3):} Highly significant (p \textless{}
  0.001) and strongly non-linear. For houses, the response to cold
  weather is strongly non-linear and highly certain, consumption
  accelerates disproportionately on the coldest days, meaning a simple
  straight-line assumption would underestimate peak heating demand.
\item
  \textbf{s(HDD):air-source (edf = 1.7):} Air-source heat pumps show a
  near-linear but slightly curved response to heating demand,
  consumption rises steadily with cold weather with only a mild bend in
  the relationship.
\item
  \textbf{s(HDD):ground-source (edf = 1.3):} Nearly linear and
  significant (p = 0.005). Ground-source heat pumps respond to cold
  weather in a stable and nearly linear fashion, making their
  consumption the most predictable of all groups.
\item
  \textbf{s(sunshine\_hours) (edf = 6.5):} Highly significant (p
  \textless{} 0.001) and strongly non-linear. More sunshine generally
  reduces consumption through passive solar gain, but the relationship
  is not a simple straight line. The effect levels off at moderate
  sunshine hours and rises again at very high values, suggesting that on
  the sunniest days some households switch their reversible heat pump to
  cooling mode, increasing electricity consumption.
\item
  \textbf{s(humidity\_avg) (edf = 5.3):} Non-linear in shape but not
  significant overall (p = 0.118). Humidity may interact with perceived
  temperature in ways not fully captured here. It is retained to enable
  a direct and controlled comparison between the LM and GAM on identical
  predictors. Dropping it did not meaningfully change the other
  coefficients.
\item
  \textbf{s(living\_area) (edf = 9.0):} Highly significant (p
  \textless{} 0.001) and the most non-linear term. Consumption does not
  scale proportionally with floor area, medium-sized homes behave
  differently from small or very large ones. Consumption peaks around
  500--600 m² and then declines sharply at very large living areas,
  which may reflect more energy-efficient construction in larger or
  newer buildings.
\end{itemize}

The parametric terms capture the baseline level shifts between groups
and are summarised in the table below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_tab }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(s\_gam}\SpecialCharTok{$}\NormalTok{p.table)}
\NormalTok{p\_tab }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}\AttributeTok{Term =} \FunctionTok{rownames}\NormalTok{(p\_tab), p\_tab)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{Term =}\NormalTok{ p\_tab}\SpecialCharTok{$}\NormalTok{Term,}
    \AttributeTok{Est =} \FunctionTok{round}\NormalTok{(p\_tab}\SpecialCharTok{$}\NormalTok{Estimate, }\DecValTok{4}\NormalTok{),}
    \AttributeTok{SE =} \FunctionTok{round}\NormalTok{(p\_tab[[}\StringTok{"Std. Error"}\NormalTok{]], }\DecValTok{4}\NormalTok{),}
    \AttributeTok{t.val =} \FunctionTok{round}\NormalTok{(p\_tab[[}\StringTok{"t value"}\NormalTok{]], }\DecValTok{2}\NormalTok{),}
    \AttributeTok{p.value =} \FunctionTok{formatC}\NormalTok{(p\_tab[[}\StringTok{"Pr(\textgreater{}|t|)"}\NormalTok{]], }\AttributeTok{digits =} \DecValTok{3}\NormalTok{, }\AttributeTok{format =} \StringTok{"g"}\NormalTok{)}
\NormalTok{  ),}
  \AttributeTok{caption =} \StringTok{"GAM – Parametric Terms"}\NormalTok{,}
  \AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Term"}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{, }\StringTok{"t{-}value"}\NormalTok{, }\StringTok{"p{-}value"}\NormalTok{),}
  \AttributeTok{row.names =} \ConstantTok{FALSE}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedright}X}
\caption{\label{tab:gam-parametric-table}GAM – Parametric Terms}\\
\toprule
Term & Estimate & Std. Error & t-value & p-value\\
\midrule
(Intercept) & 2.5659 & 0.0331 & 77.62 & 0\\
building\_typehouse & 0.0192 & 0.0331 & 0.58 & 0.562\\
heatpump\_typeground-source & -0.1437 & 0.0065 & -22.09 & 8.13e-108\\
n\_residents & 0.1297 & 0.0030 & 43.62 & 0\\
\bottomrule
\end{longtabu}

While the \texttt{by\ =} smooths allow the heating-demand curve to
differ in shape. Converting the parametric estimates with
\texttt{(exp(coef)\ -\ 1)\ ×\ 100} gives the percentage difference
relative to the reference level (flat, air-source heat pump).

\begin{itemize}
\tightlist
\item
  \textbf{Houses vs.~flats:} The parametric term for
  \texttt{building\_typehouse} is small and not statistically
  significant (p = 0.562). Once the model fits a separate heating-demand
  curve per building type, the baseline intercept gap disappears. The
  difference between building types is captured entirely by how they
  respond to cold weather, not by a flat shift.
\item
  \textbf{Ground-source vs.~air-source heat pump:} Ground-source systems
  consume 13.4\% less electricity per day, all else equal (p \textless{}
  0.001). This large reduction reflects the inherently higher efficiency
  of ground-source heat pumps across all temperature conditions.
\item
  \textbf{Number of residents:} Each additional resident adds 13.8\% to
  daily consumption (p \textless{} 0.001), confirming that occupancy is
  a meaningful driver of electricity demand.
\end{itemize}

\subsubsection{Visual Evidence}\label{visual-evidence-3}

The component plots below visualise the estimated smooth function for
each predictor, showing how each variable contributes to the predicted
log consumption independently of the others.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gratia}\SpecialCharTok{::}\FunctionTok{draw}\NormalTok{(}
\NormalTok{  model\_gam,}
  \AttributeTok{residuals =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{ci\_level =} \FloatTok{0.95}\NormalTok{,}
  \AttributeTok{smooth\_col =}\NormalTok{ clr\_primary,}
  \AttributeTok{ci\_col =}\NormalTok{ clr\_primary}
\NormalTok{) }\SpecialCharTok{\&}
\NormalTok{  report\_theme }\SpecialCharTok{\&}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{9}\NormalTok{),}
        \AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{8}\NormalTok{),}
        \AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{9}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/gam-smooth-plots-1} \end{center}

The seven panels show the estimated smooth function for each term in the
model. The y-axis is the additive contribution to
\texttt{log\_kWh\_total}, where positive values increase predicted
consumption and negative values decrease it. The shaded bands are 95\%
confidence intervals. The effective degrees of freedom (edf) on each
panel title indicates curvature. An edf of 1 is a straight line and
higher values indicate more complex shapes. The s(HDD):house smooth (edf
= 5.3) shows the most visible curvature, confirming that cold-weather
response is the main source of non-linearity for houses.

To make the by = smooths more interpretable, the plots below show the
model's predicted daily consumption on the original kWh scale, with all
other predictors held at their median values.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hdd\_grid }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(}
  \AttributeTok{heating\_degree\_days =} \FunctionTok{seq}\NormalTok{(}
    \FunctionTok{min}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heating\_degree\_days),}
    \FunctionTok{max}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heating\_degree\_days),}
    \AttributeTok{length.out =} \DecValTok{200}
\NormalTok{  ),}
  \AttributeTok{sunshine\_hours =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{sunshine\_hours),}
  \AttributeTok{humidity\_avg =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{humidity\_avg),}
  \AttributeTok{living\_area =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{living\_area),}
  \AttributeTok{n\_residents =} \FunctionTok{round}\NormalTok{(}\FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{n\_residents)),}
  \AttributeTok{building\_type =} \FunctionTok{levels}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{building\_type),}
  \AttributeTok{heatpump\_type =} \FunctionTok{levels}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heatpump\_type)[}\DecValTok{1}\NormalTok{]}
\NormalTok{)}
\NormalTok{hdd\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_gam, }\AttributeTok{newdata =}\NormalTok{ hdd\_grid, }\AttributeTok{se.fit =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{hdd\_grid}\SpecialCharTok{$}\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ hdd\_pred}\SpecialCharTok{$}\NormalTok{fit}
\NormalTok{hdd\_grid}\SpecialCharTok{$}\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ hdd\_pred}\SpecialCharTok{$}\NormalTok{se.fit}

\FunctionTok{ggplot}\NormalTok{(}
\NormalTok{  hdd\_grid,}
  \FunctionTok{aes}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ heating\_degree\_days,}
    \AttributeTok{y =} \FunctionTok{exp}\NormalTok{(fit),}
    \AttributeTok{color =}\NormalTok{ building\_type,}
    \AttributeTok{fill =}\NormalTok{ building\_type}
\NormalTok{  )}
\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_ribbon}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =} \FunctionTok{exp}\NormalTok{(fit }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se), }\AttributeTok{ymax =} \FunctionTok{exp}\NormalTok{(fit }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se)),}
    \AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{,}
    \AttributeTok{color =} \ConstantTok{NA}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GAM – Predicted Daily Consumption by Heating Demand and Building Type"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Other predictors held at median; air{-}source heat pump"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Heating Degree Days"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Predicted kWh/day"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Building type"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Building type"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =}\NormalTok{ clr\_builds) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =}\NormalTok{ clr\_builds) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/gam-pred-hdd-1} \end{center}

This plot shows how the GAM's heating-demand curve differs between
houses and flats. Both groups consume more electricity on colder days,
but houses show a steeper and more curved response, particularly at high
HDD values. This non-linearity, captured by the s(HDD):house smooth with
edf = 5.3, would have been forced into a single linear slope by the LM's
interaction term. The wider confidence band for flats at extreme cold
values reflects lower sample density there.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hp\_grid }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(}
  \AttributeTok{heating\_degree\_days =} \FunctionTok{seq}\NormalTok{(}
    \FunctionTok{min}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heating\_degree\_days),}
    \FunctionTok{max}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heating\_degree\_days),}
    \AttributeTok{length.out =} \DecValTok{200}
\NormalTok{  ),}
  \AttributeTok{sunshine\_hours =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{sunshine\_hours),}
  \AttributeTok{humidity\_avg =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{humidity\_avg),}
  \AttributeTok{living\_area =} \FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{living\_area),}
  \AttributeTok{n\_residents =} \FunctionTok{round}\NormalTok{(}\FunctionTok{median}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{n\_residents)),}
  \AttributeTok{building\_type =} \FunctionTok{levels}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{building\_type)[}\DecValTok{1}\NormalTok{],}
  \AttributeTok{heatpump\_type =} \FunctionTok{levels}\NormalTok{(gam\_train}\SpecialCharTok{$}\NormalTok{heatpump\_type)}
\NormalTok{)}
\NormalTok{hp\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_gam, }\AttributeTok{newdata =}\NormalTok{ hp\_grid, }\AttributeTok{se.fit =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{hp\_grid}\SpecialCharTok{$}\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ hp\_pred}\SpecialCharTok{$}\NormalTok{fit}
\NormalTok{hp\_grid}\SpecialCharTok{$}\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ hp\_pred}\SpecialCharTok{$}\NormalTok{se.fit}

\FunctionTok{ggplot}\NormalTok{(}
\NormalTok{  hp\_grid,}
  \FunctionTok{aes}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ heating\_degree\_days,}
    \AttributeTok{y =} \FunctionTok{exp}\NormalTok{(fit),}
    \AttributeTok{color =}\NormalTok{ heatpump\_type,}
    \AttributeTok{fill =}\NormalTok{ heatpump\_type}
\NormalTok{  )}
\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_ribbon}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =} \FunctionTok{exp}\NormalTok{(fit }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se), }\AttributeTok{ymax =} \FunctionTok{exp}\NormalTok{(fit }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se)),}
    \AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{,}
    \AttributeTok{color =} \ConstantTok{NA}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GAM – Predicted Daily Consumption by Heating Demand and Heat Pump Type"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Other predictors held at median; flat building type"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Heating Degree Days"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Predicted kWh/day"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Heat pump type"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Heat pump type"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"air{-}source"} \OtherTok{=}\NormalTok{ clr\_primary, }\StringTok{"ground{-}source"} \OtherTok{=}\NormalTok{ clr\_secondary)) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"air{-}source"} \OtherTok{=}\NormalTok{ clr\_primary, }\StringTok{"ground{-}source"} \OtherTok{=}\NormalTok{ clr\_secondary)) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/gam-pred-heatpump-1} \end{center}

This plot compares the predicted heating-demand curves for air-source
and ground-source heat pumps. Ground-source systems consume consistently
less electricity across the full range of heating demand. The
near-linear shape of both curves (reflecting low edf for these smooths)
suggests that heat pump type shifts the intercept of the heating
response more than it changes its curvature. The stable gap confirms the
large parametric coefficient for ground-source heat pumps identified
above.

\subsubsection{Model Diagnostics}\label{model-diagnostics-3}

The plots below assess how well the model fits the training data and
whether any systematic patterns remain in the residuals.

\begin{center}\includegraphics[width=0.7\linewidth]{report_files/figure-latex/gam-obs-vs-fitted-1} \end{center}

The dashed line is the ideal 1:1 line. A perfectly calibrated model
would scatter all points along it symmetrically. Systematic deviations
above or below indicate that the model consistently over- or
under-estimates in certain consumption ranges. The points follow the 1:1
line reasonably well in the mid-range, confirming the model captures the
main consumption patterns. A cluster of strongly negative observed
values around fitted = 2.5 is visible, likely representing near-zero
consumption days or data anomalies. At low fitted values the cloud sits
slightly above the reference line, indicating mild underestimation
there. Both patterns are consistent with a cross-sectional model that
cannot account for individual household behaviour.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resid\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{fitted =} \FunctionTok{fitted}\NormalTok{(model\_gam),}
  \AttributeTok{residuals =} \FunctionTok{residuals}\NormalTok{(model\_gam)}
\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(resid\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ fitted, }\AttributeTok{y =}\NormalTok{ residuals)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_primary) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_secondary, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"loess"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color =}\NormalTok{ clr\_secondary, }\AttributeTok{linewidth =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"GAM – Residuals vs. Fitted"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Fitted log(kWh\_total)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Residuals"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  report\_theme}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{report_files/figure-latex/gam-residuals-1} \end{center}

The loess smoother is approximately flat and close to zero across most
of the fitted range, indicating no major systematic bias. A slight
negative dip is visible at low fitted values and a small downward drift
appears at the high end. The vertical streaks of extreme negative
residuals around fitted = 2 correspond to the same anomalous near-zero
consumption days visible in the observed vs fitted plot. Residual
variance is broadly stable across the fitted range with no strong funnel
shape, suggesting heteroscedasticity is not a major concern.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_gam }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_gam, }\AttributeTok{newdata =}\NormalTok{ gam\_test)}
\NormalTok{actual\_log }\OtherTok{\textless{}{-}}\NormalTok{ gam\_test}\SpecialCharTok{$}\NormalTok{log\_kWh\_total}
\NormalTok{actual\_kwh }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(actual\_log)}
\NormalTok{pred\_kwh }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(pred\_gam)}

\NormalTok{gam\_mae\_kwh }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{(actual\_kwh }\SpecialCharTok{{-}}\NormalTok{ pred\_kwh))}
\NormalTok{median\_kwh }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(actual\_kwh)}
\NormalTok{mae\_pct }\OtherTok{\textless{}{-}}\NormalTok{ gam\_mae\_kwh }\SpecialCharTok{/}\NormalTok{ median\_kwh }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{r2\_gam }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}
  \FunctionTok{sum}\NormalTok{((actual\_log }\SpecialCharTok{{-}}\NormalTok{ pred\_gam)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{((actual\_log }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(actual\_log))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}
  \StringTok{"R\textbackslash{}u00b2 (test):          \%.1f\%\%}\SpecialCharTok{\textbackslash{}n}\StringTok{MAE (kWh/day):     \%.1f kWh}\SpecialCharTok{\textbackslash{}n}\StringTok{Median consumption: \%.1f kWh/day}\SpecialCharTok{\textbackslash{}n}\StringTok{MAE as \%\% of median: \%.1f\%\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
\NormalTok{  r2\_gam }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
\NormalTok{  gam\_mae\_kwh,}
\NormalTok{  median\_kwh,}
\NormalTok{  mae\_pct}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R² (test):          31.6%
## MAE (kWh/day):     10.6 kWh
## Median consumption: 20.9 kWh/day
## MAE as % of median: 50.5%
\end{verbatim}

The most interpretable performance metric here is the \textbf{mean
absolute error in kWh}. On average, the model's daily consumption
forecasts are off by \textbf{10.6 kWh}, against a median household
consumption of \textbf{20.9 kWh/day}. This means a typical prediction
error of about \textbf{51\%} of a household's usual daily consumption.
This is expected for a cross-sectional model of this type. Weather and
building characteristics capture the structural drivers of demand, but
day-to-day variation driven by individual behaviour, whether someone is
home, what appliances they use, is simply not observable from the
available predictors and represents a natural ceiling for this modelling
approach.

The \textbf{R² of 31.6\%} tells the same story from a different angle.
The eight predictors explain roughly a third of the day-to-day variation
in consumption, and the remaining two-thirds is driven by factors not
available in this dataset. Compared to the extended Linear Model (R² =
27.4\%, MAE = 10.96 kWh/day), the GAM achieves a modest improvement. R²
rises by 3.6 percentage points and MAE falls by approximately 0.4
kWh/day. This improvement is real but small, suggesting that the LM's
linear approximation is adequate for most of the predictors in this
dataset.

A note on why RMSE was not used. RMSE on the log scale is mathematically
correct but has no intuitive unit that a client can relate to. MAE in
kWh is directly actionable, and R² communicates model quality in plain
percentage terms.

\subsubsection{Key Findings}\label{key-findings-2}

\begin{itemize}
\tightlist
\item
  \textbf{Heating demand (HDD)} is non-linear for houses (edf = 5.3, p
  \textless{} 0.001), meaning the LM's linear interaction term
  understates the acceleration in consumption during the coldest days.
\item
  \textbf{HDD for flats} shows no significant smooth effect (edf = 0.8,
  p = 0.316). Flat consumption responds to cold weather in a way that is
  well described by a straight line once group-specific curves are
  allowed.
\item
  \textbf{Ground-source heat pumps} consume 13.4\% less electricity than
  air-source systems (p \textless{} 0.001).
\item
  \textbf{Each additional resident} adds 13.8\% to daily consumption (p
  \textless{} 0.001).
\item
  \textbf{Living area} is the most non-linear predictor (edf = 9.0, p
  \textless{} 0.001). Consumption does not scale proportionally with
  floor area.
\item
  The GAM achieves an R² of 31.6\% and a MAE of 10.6 kWh/day, improving
  on the extended LM by about 0.4 kWh/day.
\end{itemize}

\subsubsection{Conclusion}\label{conclusion-3}

The GAM confirms that non-linearity is present in the data, but mostly
in how houses respond to cold weather during the peak heating season.
For flats and both heat pump types, the heating-demand curve is close to
linear, meaning the extended LM captures those effects adequately. The
most actionable findings are consistent with the LM. Ground-source heat
pumps and lower occupancy reduce consumption significantly. The GAM's
modest improvement in predictive accuracy (MAE of 10.6 kWh/day versus
10.96 kWh/day for the extended LM) does not justify choosing it over the
LM when interpretability is the priority. The detailed comparison using
5-fold cross-validation is presented in the Model Comparison section.

\subsection{Neural Network (NN)}\label{nn}

\emph{Lead: Raphaël Spagolla}

\subsubsection{Objective}\label{objective-4}

The aim of this analysis is to predict whether an observation
corresponds to a high-consumption event (high\_consumption), a binary
outcome taking values 0 or 1. This is a classification problem, where
the focus is on accurately distinguishing between high- and
low-consumption cases.

From a practical perspective, reliable classification of
high-consumption events can support decision-making processes such as
resource allocation, cost management, or demand planning. Early
identification of such events allows for more efficient operational
responses.

A neural network is employed to capture potentially complex and
non-linear relationships between consumption and predictors, including
weather conditions, building characteristics, and household composition.
Model performance is evaluated based on predictive accuracy and
classification metrics derived from test data.

\subsubsection{Data Preparation}\label{data-preparation}

The dataset consists of 99,838 observations and includes variables
related to weather conditions, building characteristics, and household
composition. The response variable, \emph{high\_consumption}, is binary,
defined using each household's own 75th percentile of
\texttt{log\_kWh\_total} as the threshold --- consistent with the GLM
Binomial and SVM. By construction, exactly 25\% of each household's days
are classified as high-consumption.

To ensure valid model evaluation, the data is split into training (80\%)
and test (20\%) sets using a stratified sampling approach. This
preserves the class distribution in both subsets and avoids biased
performance estimates that could arise from imbalanced splits.

Categorical variables are transformed into dummy variables using one-hot
encoding, allowing them to be used as inputs in the neural network. In
addition, all predictors are scaled based on the training data. This
step is important for neural networks, as it improves numerical
stability and facilitates efficient training. The same transformations
are then applied to the test set to ensure consistency and prevent data
leakage.

\subsubsection{Model setup}\label{model-setup-4}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{deparse}\NormalTok{(}\FunctionTok{formula}\NormalTok{(mod\_nn)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## high_consumption ~ heating_degree_days + temp_avg + living_area +      building_typehouse + heatpump_typeground.source + has_floor_heating1 +      n_residents + is_weekend1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_nn}\SpecialCharTok{$}\NormalTok{call}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## nnet.formula(formula = high_consumption ~ ., data = train_nn, 
##     size = 25, decay = 0.05, maxit = 1000, trace = FALSE)
\end{verbatim}

The neural network is specified with an architecture of (9--25--1),
consisting of nine input nodes, one hidden layer with 25 neurons, and a
single output neuron for binary classification. This relatively simple
structure is chosen to balance model flexibility with the risk of
overfitting, allowing the network to capture non-linear relationships
without introducing unnecessary complexity.

A non-linear activation function is applied in the hidden layer,
enabling the model to learn complex patterns in the data. The output
layer produces predicted probabilities for the high-consumption class.

To improve generalisation, weight decay (set to 0.05) is included as a
regularisation mechanism. This penalises large weights and helps reduce
model variance. The network is trained using the nnet package with a
sufficient number of iterations to ensure convergence.

Overall, the chosen specification reflects a trade-off between
predictive performance and model stability, favouring a parsimonious
architecture that performs reliably on unseen data.

\subsubsection{Model Results}\label{model-results-4}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:nn-results}Neural Network Performance Metrics}\\
\toprule
Model & Accuracy & Sensitivity & Specificity & AUC\\
\midrule
Neural Network & 0.855 & 0.621 & 0.934 & 0.91\\
\bottomrule
\end{longtabu}

The neural network achieves an accuracy of approximately 0.86. Because
the binary target is defined using the 75th-percentile threshold,
roughly 75\% of observations belong to the low-consumption class; a
naive classifier that always predicts ``low'' would therefore achieve a
baseline accuracy of \(\approx 0.75\). The model's accuracy must be
assessed against this higher bar rather than a 50/50 split. The AUC of
0.91 provides a threshold-independent measure and confirms
discriminative ability beyond the class-imbalance baseline.

Specificity (0.934) exceeds sensitivity (0.621), indicating that the
model is more effective at identifying low-consumption days than
high-consumption days. This is expected given the 75/25 class imbalance:
with three times as many normal days as high-consumption days, the model
has more signal for the majority class. The lower sensitivity reflects a
higher rate of missed high-consumption events, which is the more costly
error in capacity-planning contexts.

Overall, the confusion matrix shows that the majority of observations
are correctly classified, with most predictions concentrated along the
diagonal. However, misclassifications occur in both directions,
indicating that some observations share similar characteristics across
classes.

These results indicate good overall classification performance, although
some variability remains unexplained, likely due to overlap in predictor
patterns between the two classes.

\subsubsection{Visual Evidence}\label{visual-evidence-4}

The \emph{predicted probability plot} illustrates how the neural network
separates the two classes. Observations belonging to the
high-consumption class tend to have higher predicted probabilities,
while low-consumption cases are concentrated at lower values. However,
noticeable overlap in the mid-range indicates that some observations
cannot be clearly distinguished, which explains the presence of
classification errors.

\begin{center}\includegraphics{report_files/figure-latex/nn-pred-prob-1} \end{center}

The \emph{confusion matrix} provides a direct summary of classification
performance. Most observations lie on the diagonal, confirming a high
number of correct predictions for both classes. Nevertheless, errors
occur in both directions, highlighting that class separation is not
complete.

\begin{center}\includegraphics{report_files/figure-latex/nn-confmat-1} \end{center}

The \emph{ROC curve} further evaluates model performance across all
possible classification thresholds. The curve lies clearly above the
diagonal reference line, indicating strong discriminative ability and
performance well above random classification. The steep initial increase
suggests that high true positive rates can be achieved with relatively
low false positive rates, while the flattening at higher values reflects
diminishing gains.

\begin{center}\includegraphics{report_files/figure-latex/nn_roc-1} \end{center}

\subsubsection{Model Diagnostics}\label{model-diagnostics-4}

Neural network diagnostics focus on predictive performance rather than
distributional assumptions. The chosen architecture (9--25--1) provides
a balance between flexibility and overfitting, allowing the model to
capture non-linear relationships while maintaining stable
generalisation.

The test accuracy of approximately 85.5\% indicates reasonable
generalisation to unseen data. The absence of a substantial gap between
training and test performance suggests that overfitting is limited,
although some dependence on the specific train--test split may remain.

The ROC curve confirms consistent performance across classification
thresholds and a clear improvement over random classification. However,
the observed overlap in predicted probabilities indicates that the
available predictors do not fully separate the two classes. This
suggests that model performance is constrained more by the information
content of the data than by the chosen model structure.

Alternative network configurations were explored to assess the impact of
model complexity. Increasing the number of hidden neurons led to slight
improvements in training performance but did not translate into
meaningful gains in test accuracy, indicating potential overfitting.
Simpler architectures achieved comparable results with greater
stability, supporting the choice of the 9--25--1 specification.

\subsubsection{Coefficient
Interpretation}\label{coefficient-interpretation}

Neural network weights are not directly interpretable as coefficients.
Because inputs pass through non-linear transformations across multiple
layers, no single weight carries an isolated, meaningful effect. Model
performance metrics (AUC, accuracy) and the cross-validation comparison
in the Model Comparison section serve as the practical evaluation
instead.

\subsubsection{Key Findings}\label{key-findings-3}

\begin{itemize}
\item
  The neural network achieves solid predictive performance, with an
  accuracy of approximately 85.5\%, which should be interpreted against
  the \(\approx 75\)\% naive baseline arising from the 75/25 class
  split.
\item
  The model is more effective at identifying low-consumption days than
  high- consumption days, as reflected in higher specificity compared to
  sensitivity. This is expected given the 75/25 class imbalance.
\item
  The confusion matrix and ROC curve confirm good overall classification
  ability, although not perfect.
\item
  Overlap in predicted probabilities indicates that some observations
  cannot be clearly separated, limiting maximum achievable performance.
\item
  Increasing model complexity does not lead to substantial improvements,
  suggesting that performance is primarily constrained by the available
  features rather than the model itself.
\end{itemize}

\subsubsection{Conclusion}\label{conclusion-4}

The neural network achieves solid predictive performance and
successfully captures non-linear relationships in the data. With an
accuracy of approximately 85.5\%, it demonstrates discriminative ability
above the naive \(\approx 75\)\% baseline that arises from the 75/25
class split, though the margin above that baseline is modest and
performance is primarily constrained by the available predictors rather
than model complexity.

However, the presence of overlap in predicted probabilities indicates
that the model cannot fully distinguish between the two classes.

From a practical perspective, the model can serve as a useful
decision-support tool for identifying high-consumption events, although
predictions should be interpreted with some caution due to remaining
classification uncertainty.

Further improvements are more likely to come from enhanced feature
engineering or the inclusion of additional relevant variables rather
than increasing model complexity. Cross-validation results for the
Neural Network are reported in the Model Comparison section.

\subsection{Support Vector Machine (SVM)}\label{svm}

\emph{Lead: Tharrmeehan Krishnathasan}

\subsubsection{Objective}\label{objective-5}

This section classifies each household-day as \emph{high consumption}
(top 25\% of that household's days) or \emph{normal}, a binary problem
with practical relevance: knowing which days are likely to be high-load
in advance lets grid operators and energy providers plan capacity.

An SVM is used because it can find non-linear decision boundaries via
kernel functions without requiring distributional assumptions about the
predictors. Performance is evaluated on a held-out test set using
accuracy, sensitivity, specificity, and F1 score.

\subsubsection{Data Preparation}\label{data-preparation-1}

\texttt{high\_consumption} labels a day as \emph{high} if it falls in
the top 25\% of that household's own \texttt{log\_kWh\_total}
distribution. For each of the 127 households, the 75th percentile is
computed separately, so every household contributes exactly 25\%
high-consumption days by construction.

After removing missing values, the dataset has 93,686 observations:
23,440 high-consumption days (25.0\%) and 70,246 normal days (75.0\%).
\texttt{log\_kWh\_total} is excluded to prevent data leakage; the SVM
must identify high-load days from weather and household characteristics
alone.

The data are split 80/20 into training (74,949 rows) and test (18,737
rows) using stratified sampling to keep the class ratio consistent. All
numeric predictors are standardised before training, as SVMs are
sensitive to feature scale.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X}
\caption{\label{tab:svm-class-balance}Class balance in the training set}\\
\toprule
Class & Proportion\\
\midrule
high & 0.251\\
normal & 0.749\\
\bottomrule
\end{longtabu}

\subsubsection{Model Setup}\label{model-setup-5}

Both models use a radial basis function (RBF) kernel, which maps data
into a higher-dimensional space to find non-linear decision boundaries.
This suits energy data where weather and household effects interact in
ways a linear boundary cannot capture.

\textbf{Baseline SVM:} C = 1, sigma estimated from training data. This
provides a reference for the tuned model.

\textbf{Tuned SVM:} 5-fold cross-validation over a grid of \texttt{C} ∈
\{1, 10, 100\} and \texttt{sigma} ∈ \{0.01, 0.1, 1/7\}. \texttt{C}
controls the misclassification penalty (higher = tighter fit);
\texttt{sigma} is the inverse bandwidth of the RBF kernel (higher = more
local boundaries). The combination with the highest CV accuracy is
selected.

The best parameters were C = 100, sigma = 0.1429 (= 1/7), achieving CV
accuracy of 0.8304 (Kappa = 0.4859) across the 3×3 grid.

\subsubsection{Model Results}\label{model-results-5}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:svm-eval-table}SVM model comparison on test set}\\
\toprule
Model & Accuracy & Sensitivity & Specificity & F1 Score\\
\midrule
Baseline SVM (C=1, default sigma) & 0.8512 & 0.5806 & 0.9419 & 0.6620\\
Tuned SVM (C=100, sigma=0.1429) & 0.8529 & 0.5902 & 0.9409 & 0.6681\\
\bottomrule
\end{longtabu}

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:svm-cv-table}Tuned SVM — 5-fold cross-validation performance (per-household 75th percentile threshold)}\\
\toprule
Model & CV AUC & CV Accuracy\\
\midrule
Tuned SVM (C=100, σ=0.1429) & 0.842 & 0.831\\
\bottomrule
\end{longtabu}

The tuned SVM achieves a five-fold CV AUC of \textbf{0.842} and accuracy
of \textbf{83.1\%}. The 80/20 split below adds sensitivity, specificity,
and F1.

The tuned SVM (C = 100, sigma = 0.1429) reaches \textbf{85.3\%}
accuracy, compared to 85.1\% for the baseline. The improvement is
modest: a naive all-\emph{normal} classifier would already score 74.9\%,
leaving a true gain of only 10 percentage points.

The more informative metrics are:

\textbf{Sensitivity (0.5902):} the model correctly identifies 59\% of
actual high-consumption days. Over half are missed, a meaningful
limitation in early-warning contexts where false negatives are costly.

\textbf{Specificity (0.9409):} normal days are classified correctly
94.1\% of the time. The model is conservative, flagging fewer
high-consumption days than actually occur (3605 predicted high vs.~4702
actual high in the test set).

\textbf{F1 Score (0.6681):} the harmonic mean of precision and recall
for the high class reflects the imbalance between high specificity and
low sensitivity.

\textbf{Kappa (0.5757):} moderate agreement beyond chance, improving on
the baseline (0.569) but below the 0.6 threshold for \emph{substantial}
agreement.

\subsubsection{Visual Evidence}\label{visual-evidence-5}

The confusion matrix heatmap shows the distribution of predictions
versus actual labels. Correct predictions fall on the diagonal;
off-diagonal cells are misclassifications.

\begin{center}\includegraphics{report_files/figure-latex/svm-conf-matrix-plot-1} \end{center}

The bar chart compares sensitivity and specificity for the baseline and
tuned models, showing how tuning shifts the balance between detecting
high-consumption days and avoiding false alarms.

\begin{center}\includegraphics[width=0.48\linewidth]{report_files/figure-latex/svm-metric-comparison-1} \end{center}

\subsubsection{Model Diagnostics}\label{model-diagnostics-5}

Unlike regression models, SVM diagnostics focus on generalisation
performance and modelling choices rather than distributional
assumptions.

\textbf{CV tuning results:} Across all 9 combinations, CV accuracy
ranged from 0.8071 (C=10, sigma=0.01) to 0.8304 (C=100, sigma=0.1429).
The top four combinations all involve sigma ≥ 0.1, suggesting a
moderately local kernel works best. The gain from increasing C from 10
to 100 at sigma=0.1429 is small (0.8268 → 0.8304), with diminishing
returns beyond that.

\textbf{Class separability:} Sensitivity of 59\% shows that the
available predictors (weather conditions and household characteristics)
do not reliably separate the two classes. Many high-consumption days
fall in the same feature space as normal days, an overlap that no kernel
choice can resolve.

\textbf{Tuning stability:} The best combination (C=100, sigma=0.1429)
sits at the top-right corner of the grid. Given the small step from C=10
to C=100 and genuine class overlap in the data, further tuning is
unlikely to produce meaningful sensitivity gains.

\textbf{Comparison with baseline:} The tuned model improves accuracy
(85.1\% → 85.3\%) and sensitivity (58.1\% → 59\%) over the default
parameters. The improvement is real but modest, pointing to the
predictor set as the limiting factor rather than model configuration.

\subsubsection{Key Findings}\label{key-findings-4}

\textbf{The SVM achieves reasonable accuracy but low sensitivity:} At
85.3\% accuracy, the model outperforms always predicting the majority
class (74.9\%). Sensitivity of 59\% is the bigger concern: more than
half of actual high-consumption days are missed.

\textbf{High specificity reflects a conservative classifier:}
Specificity of 94.1\% means the model rarely raises false alarms on
normal days, but this comes at the cost of missing many genuine
high-load events.

\textbf{Tuning yields real but limited improvement:} Moving from default
parameters to C=100, sigma=0.1429 improves sensitivity from 58.1\% to
59\% and accuracy from 85.1\% to 85.3\%. The gains are consistent but
small; further tuning will not resolve the core problem.

\textbf{The predictor set is the bottleneck:} Weather conditions and
static household characteristics capture only part of what drives
high-consumption days. Day-to-day within-household variation is not well
explained by the available features.

\textbf{Data leakage is avoided:} By excluding \texttt{log\_kWh\_total},
all results reflect genuine out-of-sample discriminative ability from
operationally observable inputs.

\subsubsection{Conclusion}\label{conclusion-5}

Weather conditions and household characteristics carry real signal for
classifying high-consumption days: the SVM scores roughly 8 percentage
points above the naive majority-class baseline.

At 59\% sensitivity, however, the model misses more than half of all
actual high-load days. For capacity planning or demand-response
triggering, that miss rate is too high for the model to be useful on its
own.

The limiting factor is not the model but the available features. High
and normal consumption days overlap substantially in the
weather-and-household feature space, and no kernel or regularisation
choice can separate what is genuinely mixed in the data. Richer features
would help: lagged consumption, occupancy patterns, or appliance-level
data.

Lowering the flagging threshold would recover more true positives at the
cost of more false alarms, which may be acceptable in a probabilistic
forecasting pipeline. At the default threshold, the model should not be
the sole basis for high-consumption day decisions.

\section{Model Comparison}\label{comparison}

The six models do not all share the same response variable, so a single
unified comparison table is not possible. Instead, models are grouped by
what they predict. Regression models (LM and GAM) are evaluated on
\texttt{log\_kWh\_total} using five-fold cross-validation mean absolute
error in kWh and R². Classification models (GLM Binomial, Neural
Network, SVM) are evaluated on \texttt{high\_consumption} using
five-fold CV AUC and accuracy. The GLM Poisson targets a monthly count
at a different aggregation level and is assessed separately. In all
cases, the same random fold assignment is used across models within each
group so that fold-to-fold variation cancels out and differences reflect
only model quality.

\subsection{Regression Models: LM vs
GAM}\label{regression-models-lm-vs-gam}

The table below reports five-fold cross-validation performance for the
two regression models fitted to \texttt{log\_kWh\_total}. MAE is
computed on the original kWh scale for interpretability. R² is computed
on the log scale.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:reg-comparison-table}Five-fold CV performance: regression models on log_kWh_total. MAE is on the kWh scale; R² is on the log scale.}\\
\toprule
Model & CV MAE (kWh/day) & CV R2\\
\midrule
Linear Model (extended) & 10.96 & 0.274\\
GAM (same predictors) & 10.56 & 0.310\\
\bottomrule
\end{longtabu}

\begin{center}\includegraphics{report_files/figure-latex/reg-comparison-plot-1} \end{center}

Both models use \textbf{exactly the same predictor set}: heating degree
days (interacted with building type and heat pump type), sunshine hours,
humidity, living area, and number of residents. The only difference is
functional form: the LM uses linear terms and explicit interaction
dummies, while the GAM replaces these with \texttt{by\ =} smooths. This
makes the comparison controlled and directly attributable to model
flexibility rather than predictor choice.

The GAM achieves a CV MAE of 10.56 kWh/day and an R² of 0.31, compared
to 10.96 kWh/day and R² of 0.274 for the extended LM. The GAM reduces
prediction error by 0.4 kWh/day, a roughly 3.6\% improvement, and
explains 3.6 additional percentage points of variance. The improvement
is real but modest. As the GAM smooth plots showed, the main
non-linearity is in how houses respond to extreme cold (edf = 5.3 for
s(HDD):house), but this effect does not translate into a large
out-of-sample accuracy gain. This suggests that household-level
heterogeneity, not functional form, is the primary source of unexplained
variance.

For a client who prioritises interpretability, the extended LM is a
reasonable choice: its coefficients are directly actionable and its
predictions are nearly as accurate. For a client who prioritises
predictive performance, the GAM is preferred, but the marginal gain of
0.40 kWh/day should be weighed against the added complexity of smooth
terms and the loss of a single interpretable coefficient per predictor.

\subsection{Classification Models: GLM Binomial vs SVM vs Neural
Network}\label{classification-models-glm-binomial-vs-svm-vs-neural-network}

The table below compares all three classification models. All three use
each household's own 75th percentile as the high-consumption threshold,
making results directly comparable. CV results are available for all
three models.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\caption{\label{tab:class-comparison-table}Classification model performance. All models: 5-fold CV, per-household 75th percentile threshold.}\\
\toprule
Model & CV AUC & CV Accuracy\\
\midrule
GLM Binomial & 0.830 & 0.802\\
SVM (C=100, σ=0.1429) & 0.842 & 0.831\\
Neural Network & 0.908 & 0.855\\
\bottomrule
\end{longtabu}

\begin{center}\includegraphics{report_files/figure-latex/class-comparison-plot-1} \end{center}

All three models share the same per-household 75th percentile threshold,
making them directly comparable. The GLM Binomial achieves a higher AUC
(0.83 vs 0.842) while accuracy is essentially tied (80.2\% vs 83.1\%).
The AUC gap reflects the GLM's stronger overall discrimination across
all classification thresholds. Both models correctly identify roughly
four out of five household-days. The GLM Binomial is the preferred
choice: it matches the SVM on accuracy, outperforms it on AUC, and
provides explicit odds ratios for each predictor. For a client who needs
to explain predictions (for example, when flagging a household for an
energy audit), this interpretability advantage is directly actionable.

\subsection{GLM Poisson (Standalone)}\label{glm-poisson-standalone}

The GLM Poisson models \texttt{n\_high\_days} at the household--month
level and cannot be placed in either comparison table. It is evaluated
separately via five-fold CV RMSE on the count scale.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}

\CommentTok{\# Extract formula cleanly — detach from model environment to avoid memory bleed}
\NormalTok{cv\_form }\OtherTok{\textless{}{-}} \FunctionTok{as.formula}\NormalTok{(}
  \FunctionTok{deparse}\NormalTok{(}\FunctionTok{formula}\NormalTok{(mod\_pois)),}
  \AttributeTok{env =} \FunctionTok{baseenv}\NormalTok{()}
\NormalTok{)}

\NormalTok{n          }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(dat\_count)}
\NormalTok{folds      }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\AttributeTok{length.out =}\NormalTok{ n))}
\NormalTok{rmse\_folds }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{5}\NormalTok{)}

\ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) \{}
\NormalTok{  train\_k }\OtherTok{\textless{}{-}}\NormalTok{ dat\_count[folds }\SpecialCharTok{!=}\NormalTok{ k, ]}
\NormalTok{  test\_k  }\OtherTok{\textless{}{-}}\NormalTok{ dat\_count[folds }\SpecialCharTok{==}\NormalTok{ k, ]}

\NormalTok{  fit\_k }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}
\NormalTok{    cv\_form,}
    \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
    \AttributeTok{offset =} \FunctionTok{log}\NormalTok{(n\_days),}
    \AttributeTok{data   =}\NormalTok{ train\_k,}
    \AttributeTok{model  =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{x      =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{y      =} \ConstantTok{FALSE}
\NormalTok{  )}

\NormalTok{  pred\_k        }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(fit\_k, }\AttributeTok{newdata =}\NormalTok{ test\_k, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{  rmse\_folds[k] }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((test\_k}\SpecialCharTok{$}\NormalTok{n\_high\_days }\SpecialCharTok{{-}}\NormalTok{ pred\_k)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
  \FunctionTok{rm}\NormalTok{(fit\_k, train\_k, test\_k)}
  \FunctionTok{gc}\NormalTok{()}
\NormalTok{\}}

\NormalTok{pois\_cv\_rmse }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(rmse\_folds), }\DecValTok{3}\NormalTok{)}
\NormalTok{pois\_cv\_sd   }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(rmse\_folds),   }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The five-fold CV RMSE is 9.48 days (SD = 0.31). Given that
\texttt{n\_high\_days} ranges from 0 to \textasciitilde30, this reflects
moderate prediction error on the count scale.

\textbf{Limitation.} This RMSE is not directly comparable to any other
metric in this report: the unit of observation is a household--month and
the response is a raw count. Cross-model ranking would be misleading.

Across all six models, interpretability and predictive performance trade
off consistently. The LM, GAMs, and GLM Poisson offer transparent,
coefficient-based explanations but leave more variance unexplained. The
SVM and Neural Network improve accuracy but are effectively black boxes.
The GLM Binomial sits in between --- log-odds coefficients remain
interpretable while classification performance is competitive. The right
choice depends on whether the use case demands explainability or
accuracy.

\section{Conclusions}\label{conclusions}

Across 127 Swiss households monitored daily from 2022 to 2024, cold
weather is the strongest and most consistent driver of electricity
consumption. The relationship is non-linear for houses: consumption
accelerates sharply on the coldest winter days, while no statistically
detectable non-linear cold-weather response was found for flats. The
single most actionable finding for an energy supplier or grid operator
is heat pump type. Households with ground-source heat pumps use
approximately 13\% less electricity per day than those with air-source
systems, holding all else equal, and this difference is stable across
seasons and building types. Occupancy also matters: every additional
resident adds roughly 14\% to daily demand, which suggests that family
size should be a key variable in any demand forecasting or household
segmentation tool.

On the modelling side, the Generalised Additive Model achieved the best
predictive accuracy for daily consumption (mean error of 10.6 kWh/day,
R² of 31\%), improving on the extended Linear Model (11.0 kWh/day, R² of
27\%) by capturing the non-linear cold-weather response of houses. The
improvement is real but moderate: both models leave roughly two-thirds
of day-to-day variation unexplained, which reflects individual household
behaviour that weather and building characteristics alone cannot
predict. For classification of high- consumption days, the GLM Binomial
performed best (AUC = 0.83, accuracy = 80.2\%) with the SVM close behind
(AUC = 0.842, accuracy = 83.1\%). For a client prioritising
transparency, the GLM Binomial is the recommended model: it identifies
high-demand household-days with good accuracy and explains exactly why
each prediction was made. The Neural Network also achieved competitive
results (AUC = 0.908, accuracy = 85.5\%), evaluated under the same
per-household 75th percentile threshold. The clearest practical takeaway
is that upgrading from air-source to ground-source heat pumps is the
intervention most likely to reduce peak demand, and that larger
households with air-source systems should be the first target for
efficiency programmes.

\section{Use of Generative AI}\label{ai}

Generative AI tools (primarily Claude and GitHub Copilot) were used
throughout this project for code generation, debugging, and text
drafting. Concretely, AI assisted with writing R code for data
preprocessing pipelines, model fitting wrappers, cross-validation loops,
and visualisation. It also helped explain statistical concepts such as
overdispersion in Poisson models, the interpretation of GAM smooth
terms, and the role of the cost and kernel bandwidth parameters in SVMs.
Straightforward, well-scoped tasks were handled reliably: generating
boilerplate ggplot2 code, converting between data formats, and producing
first drafts of prose that described model outputs. More demanding tasks
required significant human oversight: AI-generated cross-validation code
contained subtle bugs (for example, returning single-column data frames
instead of vectors, and using a mismatched response variable across
models), and AI-drafted coefficient interpretations occasionally
overstated certainty or omitted important caveats. Certain tasks were
not delegable at all --- the substantive analytical decisions, such as
choosing which threshold to use for the high-consumption binary response
and how to handle the incompatibility between the Neural Network's
pre-computed predictions and the rest of the CV pipeline, required
domain judgement that the AI could frame but not resolve. All
AI-generated code was reviewed, tested, and where necessary corrected
before being incorporated, and all interpretive prose was verified
against the actual model output rather than accepted at face value.

\end{document}
